apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: nginx
    podtype: D
spec:
  schedulerName: rl-scheduler
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
